/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package for_gratefullness_group.new_package_1;

/**
 *
 * @author VTMEDICS
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import for_gratefullness_group.DASHBOARD_GRATEFULLNESS;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author YPMEDICS
 */
public class GRATEFULNESS_DASHBOARD extends javax.swing.JFrame {

    /** Creates new form GRATEFULNESS_DASHBOARD */
    public GRATEFULNESS_DASHBOARD() {
        initComponents();
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\YPMEDICS\\Documents\\NetBeansProjects\\GRATEFULNESS_PROGRAM\\src\\gratefulness_program1\\1.png"));
        Thread t = new Thread(new Runnable(){
            @Override
            public void run() {
                int i;
            for(i=0; i<101;i++){
            progress.setValue(i);
                try {
                    int arr[]={50,1000,150,100,30,20,10,5,80};
                    int b=(1+(int)(Math.random()*9));
                    Thread.sleep(arr[b-1]);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(GRATEFULNESS_DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            dispose(); 
            new DASHBOARD_GRATEFULLNESS().setVisible(true);
        }
            
        });
        
       t.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WELCOME_GRATEFULLNESS");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(1375, 750));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1340, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1340, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1375, 750));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/for_gratefullness_group/new_package_1/1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 150, 520, 350);

        progress.setBackground(new java.awt.Color(255, 255, 255));
        progress.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        progress.setForeground(new java.awt.Color(0, 0, 0));
        progress.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "LOADING", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        progress.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        progress.setName(""); // NOI18N
        progress.setStringPainted(true);
        jPanel1.add(progress);
        progress.setBounds(530, 550, 338, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progress;
    // End of variables declaration                   

}
